/**
 * Client-side translations for Reelly catalogue fields when the API has no PT copy
 * (Reelly confirms en-us, ar, fr, de, etc. — not Portuguese).
 * Keys are normalized: lowercase, spaces/hyphens → underscores.
 */
export const REELLY_TERMS = {
  en: {
    saleStatuses: {},
    constructionStatuses: {},
    amenities: {},
    unitTypes: {},
  },
  pt: {
    saleStatuses: {
      on_sale: 'À venda',
      on_sale_now: 'À venda',
      available: 'Disponível',
      available_for_sale: 'Disponível para venda',
      pre_launch: 'Pré-lançamento',
      prelaunch: 'Pré-lançamento',
      coming_soon: 'Em breve',
      launch: 'Lançamento',
      launched: 'Lançado',
      sold_out: 'Esgotado',
      sold: 'Vendido',
      booking: 'Reserva aberta',
      open_for_booking: 'Reserva aberta',
      registration: 'Registo aberto',
      registration_open: 'Registo aberto',
      announcement: 'Anunciado',
      announced: 'Anunciado',
    },
    constructionStatuses: {
      under_construction: 'Em construção',
      off_plan: 'Off-plan',
      offplan: 'Off-plan',
      planned: 'Planificado',
      completed: 'Concluído',
      ready: 'Pronto',
      handover: 'Entrega',
      handed_over: 'Entregue',
      construction: 'Em construção',
      launched: 'Lançado',
    },
    unitTypes: {
      apartment: 'Apartamento',
      villa: 'Moradia',
      townhouse: 'Townhouse',
      penthouse: 'Penthouse',
      studio: 'Estúdio',
      duplex: 'Duplex',
      loft: 'Loft',
      office: 'Escritório',
      retail: 'Comercial',
      commercial: 'Comercial',
    },
    amenities: {
      swimming_pool: 'Piscina',
      pool: 'Piscina',
      gym: 'Ginásio',
      fitness_center: 'Ginásio',
      fitness_centre: 'Ginásio',
      spa: 'Spa',
      sauna: 'Sauna',
      steam_room: 'Banho de vapor',
      jacuzzi: 'Jacuzzi',
      kids_play_area: 'Parque infantil',
      children_play_area: 'Parque infantil',
      playground: 'Parque infantil',
      landscaped_gardens: 'Jardins paisagísticos',
      garden: 'Jardim',
      parks: 'Parques',
      bbq_area: 'Zona de churrasco',
      barbecue_area: 'Zona de churrasco',
      security: 'Segurança',
      '24_7_security': 'Segurança 24/7',
      concierge: 'Concierge',
      parking: 'Estacionamento',
      covered_parking: 'Estacionamento coberto',
      basement_parking: 'Estacionamento subterrâneo',
      retail_outlets: 'Lojas',
      shops: 'Lojas',
      supermarket: 'Supermercado',
      restaurant: 'Restaurante',
      cafes: 'Cafés',
      cafe: 'Café',
      lounge: 'Lounge',
      cinema: 'Cinema',
      library: 'Biblioteca',
      business_center: 'Centro de negócios',
      business_centre: 'Centro de negócios',
      meeting_room: 'Sala de reuniões',
      co_working_space: 'Espaço de coworking',
      coworking: 'Coworking',
      tennis_court: 'Campo de ténis',
      basketball_court: 'Campo de basquetebol',
      jogging_track: 'Pista de corrida',
      running_track: 'Pista de corrida',
      cycling_track: 'Pista de ciclismo',
      yoga_room: 'Sala de yoga',
      meditation_room: 'Sala de meditação',
      beach_access: 'Acesso à praia',
      private_beach: 'Praia privada',
      marina: 'Marina',
      waterfront: 'Frente de água',
      sea_view: 'Vista mar',
      balcony: 'Varanda',
      terrace: 'Terraço',
      rooftop_terrace: 'Terraço no último piso',
      smart_home: 'Casa inteligente',
      central_ac: 'Ar condicionado central',
      air_conditioning: 'Ar condicionado',
      maid_room: 'Quarto de empregada',
      storage_room: 'Arrecadação',
      laundry_room: 'Lavandaria',
      pet_friendly: 'Aceita animais',
      electric_vehicle_charging: 'Carregamento de veículos elétricos',
      ev_charging: 'Carregamento EV',
      mosque: 'Mesquita',
      prayer_room: 'Sala de oração',
      clubhouse: 'Clube',
      community_center: 'Centro comunitário',
      community_centre: 'Centro comunitário',
      health_club: 'Clube de saúde',
      wellness_center: 'Centro de bem-estar',
      wellness_centre: 'Centro de bem-estar',
      valet_parking: 'Estacionamento com manobrista',
      reception: 'Receção',
      lobby: 'Lobby',
      elevator: 'Elevador',
      lifts: 'Elevadores',
      high_speed_elevators: 'Elevadores de alta velocidade',
      wifi: 'Wi‑Fi',
      wi_fi: 'Wi‑Fi',
      broadband: 'Internet de banda larga',
    },
  },
}
